version: '3.8'

services:
  jenkins:
    build: .
    container_name: jenkins-server
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - C:/Users/hayar/shared:/shared
    restart: unless-stopped
